/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[*********************100%***********************]  1 of 1 completed
(2776,)
(2776,)
(2776,)
{'AAPL': Date
2012-05-18 00:00:00+00:00     18.373452
2012-05-21 00:00:00+00:00     18.357676
2012-05-22 00:00:00+00:00     18.341911
2012-05-23 00:00:00+00:00     18.326157
2012-05-24 00:00:00+00:00     18.310413
                                ...
2023-05-24 00:00:00+00:00    161.422796
2023-05-25 00:00:00+00:00    161.480431
2023-05-26 00:00:00+00:00    161.538061
2023-05-30 00:00:00+00:00    161.595688
2023-05-31 00:00:00+00:00    161.653312
Name: trend, Length: 2776, dtype: float64}
{'AAPL': Date
2012-05-18 00:00:00+00:00    -2.037151
2012-05-21 00:00:00+00:00    -1.339883
2012-05-22 00:00:00+00:00    -1.369425
2012-05-23 00:00:00+00:00    -1.131666
2012-05-24 00:00:00+00:00    -1.129784
                               ...
2023-05-24 00:00:00+00:00    -6.710189
2023-05-25 00:00:00+00:00   -10.178110
2023-05-26 00:00:00+00:00   -10.052280
2023-05-30 00:00:00+00:00    -6.308044
2023-05-31 00:00:00+00:00    -3.033744
Name: season, Length: 2776, dtype: float64}
[*********************100%***********************]  1 of 1 completed
GOOGL
[*********************100%***********************]  1 of 1 completed
META
[*********************100%***********************]  1 of 1 completed
AMZN
[*********************100%***********************]  1 of 1 completed
MSFT
[32m[I 2024-11-01 21:59:02,418][0m A new study created in memory with name: no-name-6c643701-6391-43ae-b175-91b40069fd63[0m
/data/student/k2110261/Multi-iTransformer/optunademo.py:91: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-6, 1e-3)
[33m[W 2024-11-01 21:59:02,625][0m Trial 0 failed with parameters: {'learning_rate': 0.0005636404777201578, 'batch_size': 101, 'step_size': 13, 'gamma': 0.7528349322760104, 'depth': 5, 'dim': 183} because of the following error: NameError("name 'train_data' is not defined").[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 125, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
                                       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 119, in objective
    model, train_data, valid_data, optimizer, criterion, scheduler, batch_size, observation_period_num[component])
           ^^^^^^^^^^
NameError: name 'train_data' is not defined. Did you mean: 'train_rates'?
[33m[W 2024-11-01 21:59:02,628][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 125, in <module>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
    ~~~~~~~~~^
        study=self,
        ^^^^^^^^^^^
    ...<7 lines>...
        show_progress_bar=show_progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
    ~~~~~~~~~~~~~~~~~~~~^
        study,
        ^^^^^^
    ...<8 lines>...
        progress_bar=progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 125, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
                                       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 119, in objective
    model, train_data, valid_data, optimizer, criterion, scheduler, batch_size, observation_period_num[component])
           ^^^^^^^^^^
NameError: name 'train_data' is not defined. Did you mean: 'train_rates'?
