[32m[I 2025-01-13 18:13:23,430][0m A new study created in memory with name: no-name-2fce3b8a-9a02-48e1-a4f6-c70568367df2[0m
[32m[I 2025-01-13 18:13:24,290][0m Trial 0 finished with value: 0.02944390673039487 and parameters: {'observation_period_num': 147, 'train_rates': 0.8870444375994246, 'learning_rate': 0.0006670820930318078, 'batch_size': 256, 'step_size': 11, 'gamma': 0.9458581410455852}. Best is trial 0 with value: 0.02944390673039487.[0m
[32m[I 2025-01-13 18:13:24,291][0m A new study created in memory with name: no-name-ad731725-5872-4887-aec0-3de00191cbd3[0m
[32m[I 2025-01-13 18:13:26,938][0m Trial 0 finished with value: 0.09871268902934903 and parameters: {'observation_period_num': 183, 'train_rates': 0.7979673533676418, 'learning_rate': 0.00010368600358490807, 'batch_size': 21, 'step_size': 10, 'gamma': 0.8930158655166807}. Best is trial 0 with value: 0.09871268902934903.[0m
[32m[I 2025-01-13 18:13:26,938][0m A new study created in memory with name: no-name-a6346d8d-4078-46b4-8916-fc1ca7d9c72e[0m
[33m[W 2025-01-13 18:13:27,604][0m Trial 0 failed with parameters: {'observation_period_num': 143, 'train_rates': 0.8308719930505191, 'learning_rate': 2.4139587089843216e-05, 'batch_size': 118, 'step_size': 12, 'gamma': 0.9715634972957233} because of the following error: KeyboardInterrupt().[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 40, in train
    loss.backward()  # ÈÄÜ‰ºùÊí≠
    ^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
[33m[W 2025-01-13 18:13:27,784][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <module>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 40, in train
    loss.backward()  # ÈÄÜ‰ºùÊí≠
    ^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
