[32m[I 2025-01-13 18:03:08,867][0m A new study created in memory with name: no-name-3cc8512a-6031-4f04-9f81-e242243b601f[0m
Non-A100 GPU detected, using math or mem efficient attention if input tensor is on cuda
[32m[I 2025-01-13 18:03:44,119][0m Trial 0 finished with value: 0.37934324122424234 and parameters: {'observation_period_num': 68, 'train_rates': 0.7517461475862083, 'learning_rate': 0.00030162459582782524, 'batch_size': 131, 'step_size': 9, 'gamma': 0.8983657437978452}. Best is trial 0 with value: 0.37934324122424234.[0m
[32m[I 2025-01-13 18:04:10,767][0m Trial 1 finished with value: 0.13590703904628754 and parameters: {'observation_period_num': 138, 'train_rates': 0.9534492565616546, 'learning_rate': 2.937351730066907e-05, 'batch_size': 219, 'step_size': 10, 'gamma': 0.84156238446908}. Best is trial 1 with value: 0.13590703904628754.[0m
[32m[I 2025-01-13 18:04:31,375][0m Trial 2 finished with value: 0.15115271508693695 and parameters: {'observation_period_num': 193, 'train_rates': 0.921167368324397, 'learning_rate': 0.0002474522685406908, 'batch_size': 240, 'step_size': 12, 'gamma': 0.9070356968286463}. Best is trial 1 with value: 0.13590703904628754.[0m
[33m[W 2025-01-13 18:05:10,976][0m Trial 3 failed with parameters: {'observation_period_num': 43, 'train_rates': 0.6328073548599962, 'learning_rate': 3.6192373260916186e-06, 'batch_size': 62, 'step_size': 11, 'gamma': 0.9613857100417919} because of the following error: KeyboardInterrupt().[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 40, in train
    loss.backward()  # ÈÄÜ‰ºùÊí≠
    ^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
[33m[W 2025-01-13 18:05:10,992][0m Trial 3 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <module>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 205, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/single.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 40, in train
    loss.backward()  # ÈÄÜ‰ºùÊí≠
    ^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
