/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[*********************100%***********************]  1 of 1 completed
Ticker                           AAPL
Date
2012-05-18 00:00:00+00:00   15.996171
2012-05-21 00:00:00+00:00   16.928108
2012-05-22 00:00:00+00:00   16.798122
2012-05-23 00:00:00+00:00   17.207994
2012-05-24 00:00:00+00:00   17.049952
...                               ...
2023-05-24 00:00:00+00:00  170.734604
2023-05-25 00:00:00+00:00  171.877197
2023-05-26 00:00:00+00:00  174.301498
2023-05-30 00:00:00+00:00  176.159470
2023-05-31 00:00:00+00:00  176.109802

[2776 rows x 1 columns]
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[32m[I 2024-11-05 03:08:40,504][0m A new study created in memory with name: no-name-2660cdb8-2ce2-427f-acd2-890b92767eee[0m
/data/student/k2110261/Multi-iTransformer/optunademo.py:101: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-6, 1e-3)
/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
[33m[W 2024-11-05 03:08:41,586][0m Trial 0 failed with parameters: {'learning_rate': 0.00023026002390066997, 'batch_size': 51, 'step_size': 8, 'gamma': 0.7683464075208472, 'depth': 5, 'dim': 28} because of the following error: NameError("name 'valid_loss_resid' is not defined").[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 144, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=100)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 135, in objective
    earlystopping(valid_loss_resid, model_resid)
                  ^^^^^^^^^^^^^^^^
NameError: name 'valid_loss_resid' is not defined
[33m[W 2024-11-05 03:08:41,587][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 144, in <module>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=100)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 144, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=100)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 135, in objective
    earlystopping(valid_loss_resid, model_resid)
                  ^^^^^^^^^^^^^^^^
NameError: name 'valid_loss_resid' is not defined
